version: "3.7"

networks:
  tokemo:
    name: tokemo
    driver: bridge

services:
  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - $HOME/data/mysql:/var/lib/mysql
    networks:
      - tokemo
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $HOME/data/nasa/:/usr/share/nginx/html/nasa
    networks:
      - tokemo

  # wp:
  #   build:
  #     context: ./requirements/wordpress
  #     dockerfile: Dockerfile
  #   environment:
  #     WORDPRESS_DB_HOST: mariadb
  #     WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
  #     WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
  #     WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ../../data/wordpress/:/var/www/html
  #   networks:
  #     - tokemo


  # wordpress:
  #   image: wordpress
  #   # image: nmota-bu_wp:0.0.2
  #   # build:  
  #   #   context: ./requirements/wordpress
  #   #   dockerfile: Dockerfile
  #   environment:
  #     WORDPRESS_DB_HOST: mariadb
  #     WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
  #     WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
  #     WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  #   volumes:
  #     # - ./tools/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
  #     - ../../data/wordpress:/var/www/html
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - tokemo

