version: "3.7"

services:
  mariadb:
    command: /bin/sh -c "apk update && apk add mariadb mariadb-client && mkdir -p /var/lib/mysql && chown -R mysql:mysql /var/lib/mysql && mysql_install_db --user=mysql --ldata=/var/lib/mysql && mysqld_safe"
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    container_name: db
    restart: always
    env_file:
     - .env
    ports:
      - "3306:3306"
    volumes:
      - $HOME/data/mysql:/var/lib/mysql
    networks:
      - tokemo
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
        

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $HOME/data/nasa:/usr/share/nginx/html/nasa
    networks:
      - tokemo

  wordpress:
      container_name: wp
      build: ./requirements/wordpress
      depends_on:
      - mariadb
      volumes:
      - $HOME/data/wordpress:/var/www/html
      restart: always
      networks:
      - tokemo
      env_file:
      - .env

networks:
  tokemo:
    driver: bridge

  # wp:
  #   build:
  #     context: ./requirements/wordpress
  #     dockerfile: Dockerfile
  #   environment:
  #     WORDPRESS_DB_HOST: mariadb
  #     WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
  #     WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
  #     WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - $HOME/data/wordpress/:/var/www/html
  #   networks:
  #     - tokemo


  # wordpress:
  #   image: wordpress
  #   # image: nmota-bu_wp:0.0.2
  #   # build:  
  #   #   context: ./requirements/wordpress
  #   #   dockerfile: Dockerfile
  #   environment:
  #     WORDPRESS_DB_HOST: mariadb
  #     WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
  #     WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
  #     WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  #   volumes:
  #     # - ./tools/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
  #     - ../../data/wordpress:/var/www/html
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - tokemo

