version: "3.7"

services:
  mariadb:
    # command: /bin/sh -c "apk update && apk add mariadb mariadb-client && mkdir -p /var/lib/mysql && chown -R mysql:mysql /var/lib/mysql && mysql_install_db --user=mysql --ldata=/var/lib/mysql && mysqld_safe"
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    container_name: db
    restart: always
    env_file:
     - .env
    ports:
      - "3306:3306"
    volumes:
      - $HOME/data/mysql:/var/lib/mysql
    networks:
      - tokemo
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
        

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $HOME/data/nasa:/var/www/nasa
      - $HOME/data/wordpress:/var/www/wp

    networks:
      - tokemo

  wordpress:
      container_name: wp
      build: ./requirements/wordpress
      depends_on:
      - mariadb
      volumes:
      - $HOME/data/wordpress:/var/www/html
      restart: always
      networks:
      - tokemo
      env_file:
      - .env

networks:
  tokemo:
    driver: bridge

