#!/bin/sh


if mysql -u "root" -p"${MYSQL_ROOT_PASSWORD}" -e "CREATE DATABASE IF NOT EXISTS ${WORDPRESS_DB_NAME}; \
  CREATE USER IF NOT EXISTS '${WORDPRESS_DB_USER}'@'localhost' IDENTIFIED BY '${WORDPRESS_DB_PASSWORD}'; \
  GRANT ALL PRIVILEGES ON *.* TO 'root'@'myadm.srcs_tokemo' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}' WITH GRANT OPTION; \
  GRANT ALL PRIVILEGES ON ${WORDPRESS_DB_NAME}.* TO '${WORDPRESS_DB_USER}'@'localhost'; \
  GRANT ALL PRIVILEGES ON *.* TO 'root'@'adminer.srcs_tokemo' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}' WITH GRANT OPTION; \
  GRANT ALL PRIVILEGES ON wordpress.* TO '${WORDPRESS_DB_USER}'@'localhost'; \
  GRANT ALL PRIVILEGES ON *.* TO '${WORDPRESS_DB_USER}'@'wp.srcs_tokemo' IDENTIFIED BY '${WORDPRESS_DB_PASSWORD}' WITH GRANT OPTION; \
  GRANT ALL PRIVILEGES ON ${WORDPRESS_DB_NAME}.* TO '${WORDPRESS_DB_USER}'@'wp.srcs_tokemo' IDENTIFIED BY '${WORDPRESS_DB_PASSWORD}'; \
  FLUSH PRIVILEGES;"; then
  echo "Todo un éxito."
else
  echo "Error al crear la base de datos o el usuario."
  exit 1
fi
